version: "3.8"

services:
  web:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
      - api
