version: "3.8"

services:
  web:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
